### ISSUE TITLE
Get storage for VM files

### ISSUE THREAD

**Issue by cgivre** [darklabsdev/Merlin-VM#4]
We need some storage for the VM binary that is publicly accessible.

**Comment by amitsaha** [comment]
Do you mean the VM image?

**Comment by cgivre** [comment]
Yes.  We need an AWS instance or something better than my Google drive to host it.

**Comment by amitsaha** [comment]
Amazon S3?

**Comment by ch3ckmat3** [comment]
Why not use BTSync (https://www.getsync.com/) and share the folder's read-only key like this http://btsynckeys.com/.

This way, we can use own storage to host and share the VM's image and have its updates pushed automatically :)
