### ISSUE TITLE
Password of the VM Users

### ISSUE THREAD

**Issue by ch3ckmat3** [darklabsdev/Merlin-VM#5]
Can we have the passwords of the VM users, to be able to make changes in the OS etc.?

Thanks.

**Comment by cgivre** [comment]
Hi Sohail, 
The password for everything is ‘merlinuser’.  Any username is also ‘merlinuser’.  There is another account which you shouldn’t really ever have to mess with called ‘hduser’ and the password is ‘hadoop’.
— C

**Comment by ch3ckmat3** [comment]
Thanks @cgivre :+1:
